### ISSUE TITLE
Caused by: java.lang.RuntimeException: 

### ISSUE THREAD

**Issue by zhongya666** [GoogleChrome/cronet-sample#23]
All available Cronet providers are disabled. A provider should be enabled before it can be used.

**Comment by zhongya666** [comment]
如果无法通过 Google Play 服务加载 Cronet，则只能使用 Cronet API 的一个性能不那么出色的实现。要使用此备用实现，请使用 org.chromium.net:cronet-fallback 并调用 [new JavaCronetProvider(context).createBuilder()](https://cs.chromium.org/chromium/src/components/cronet/android/java/src/org/chromium/net/impl/JavaCronetProvider.java?rcl=083c8628750635ebdb2e1fa303c26141d4ac8773&l=31)。

**Comment by ag2s20150909** [comment]
> 如果无法通过 Google Play 服务加载 Cronet，则只能使用 Cronet API 的一个性能实现不那么出色。要使用此备用实现，请 org.chromium.net:cronet-fallback 并调用[new JavaCronetProvider(context).createBuilder ()](https://cs.chromium.org/chromium/src/components/cronet/android/java/src/org/chromium/net/impl/JavaCronetProvider.java?rcl=083c8628750635ebdb2e1fa303c26141d4ac8773&l=31)。

`implementation 'org.chromium.net:cronet-embedded:105.5195.68'`
