### ISSUE TITLE
After QUIC is enabled, the QUIC protocol is not implemented

### ISSUE THREAD

**Issue by 0barman** [GoogleChrome/cronet-sample#25]
Only QUIC support is turned on. When using wireshark to analyze this demo, I did not see the packet content of the QUIC protocol. The 105 version of Cronet I compiled on Ubuntu also doesn't see the QUIC package contents. What is the reason? Tested with Samsung phone.

**Comment by 0barman** [comment]
Neither the demo nor Cronet(version 105) has QUIC enabled, and HTTP requests are still used. How to make the request only perform QUIC requests. It's very anxious. Thanks for the quick answer

**Comment by ag2s20150909** [comment]
`implementation 'org.chromium.net:cronet-embedded:105.5195.68'`

 https://github.com/chromium/chromium/blob/3f1ea440df93a4b2bda825e033f733bba25b2f80/components/cronet/android/api/src/org/chromium/net/CronetEngine.java#L238
